[package]
name = "gizmo"
version = "0.1.0"
authors = ["monomadic <deathdisco@protonmail.com>"]
edition = "2018"

[dependencies]
glob = "*"
nom = { version = "5.1.1", features = ["std"] }
yaml-rust = "0.4"
markdown = "0.2"
