[package]
name = "astryx"
version = "0.1.0"
authors = ["monomadic <deathdisco@protonmail.com>"]
edition = "2018"

[dependencies]
glob = "0.3.0"
nom = { version = "5.1.1", features = ["std"] }
yaml-rust = "0.4"
pulldown-cmark = "*"
syntect = "4.2.0"
rctree = "0.3.3"
parser = { path = "components/parser" }

[workspace]
members = ["components/cli", "components/search", "components/parser"]
