[package]
name = "astryx"
version = "0.1.0"
authors = ["monomadic <deathdisco@protonmail.com>"]
edition = "2018"

[dependencies]
glob = "0.3.0"
nom = { version = "5.1.1", features = ["std"] }
yaml-rust = "0.4"
syntect = "4.2.0"
rctree = "0.3.3"
parser = { path = "components/parser" }
interpreter = { path = "components/interpreter" }
html = { path = "components/html" }
simple-server = "0.4.0"
structopt = "0.3"

[workspace]
members = [
  "components/interpreter",
  "components/search",
  "components/parser",
  "components/html"
]
