[package]
name = "models"
version = "0.1.0"
authors = ["monomadic <deathdisco@protonmail.com>"]
edition = "2018"

[dependencies]
rctree = "0.3.3"
html = { path = "../html" }
error = { path = "../error" }
yaml-rust = "0.4"
