[package]
name = "astryx-cli"
version = "0.1.0"
authors = ["monomadic <deathdisco@protonmail.com>"]
edition = "2018"

[[bin]]
name = "astryx"
path = "src/main.rs"

[dependencies]
simple-server = "0.4.0"
structopt = "0.3"
astryx = { path = ".." }
