[package]
name = "repl"
version = "0.1.0"
authors = ["monomadic <deathdisco@protonmail.com>"]
edition = "2018"

[dependencies]
rustyline = "6.3.0"
interpreter = { path = "../interpreter" }
parser = { path = "../parser" }
