[package]
name = "parser"
version = "0.1.0"
authors = ["monomadic <deathdisco@protonmail.com>"]
edition = "2018"

[dependencies]
nom = { version = "6.0.1", features = ["std"] }
yaml-rust = "0.4"
nom_locate = "3.0.0"
rctree = "0.3.3"
error = { path = "../error" }
